apiVersion: v1
kind: Service
metadata:
  name: agromind-serving
  namespace: agromind
spec:
  clusterIP: 10.43.83.65
  clusterIPs:
  - 10.43.83.65
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
  selector:
    app: agromind-vllm
  sessionAffinity: None
  type: ClusterIP
